---
#  test
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  #mem: circleci/rememborb@0.0.1
  env: christeredvartsen/persist-env@0.1.0
version: 2.1
jobs:
  image_tag:
      machine: true
      steps:
        - env/set-env-var:
            var-name: IMAGE_TAG
            var-value: $(cat  VERSION.txt | tr -d '\n')
        - env/persist-env

  echo_tag:
    machine: true
    steps:
      - env/attach-env
      - run:
          name: Use env var set in build job
          command: echo $IMAGE_TAG

  hadolint:
    docker:
      - image: 'hadolint/hadolint:latest-debian'
    steps:
      - 'checkout'
      - run:
          name: 'run hadolint'
          command: 'hadolint Dockerfile'
workflows:
  version: 2
  lint:
    jobs:
      # - yamllint:
      #     filters:
      #       branches:
      #         ignore:
      #           - 'master'
      - 'hadolint'
  build_and_push_image:
    jobs:
      - echo_tag
      - aws-ecr/build-and-push-image:
          requires:
            - echo_tag
          account-url: AWS_ECR_ACCOUNT_URL
          context: 'aws-ecr-pull-push'
          create-repo: false
          dockerfile: 'Dockerfile'
          profile-name: 'default'
          region: AWS_DEFAULT_REGION
          repo: '274118048627.dkr.ecr.us-east-2.amazonaws.com/awscli'
          tag: $IMAGE_TAG
