---
#test
orbs:
  aws-ecr: circleci/aws-ecr@6.7.0
  mem: circleci/rememborb@0.0.1
version: 2.1
jobs:
  image_tag:
    docker:
      - image: 'circleci/python:3.7'
    steps:
      - mem/remember:
          env_var: IMAGE_TAG
          value: $(cat  VERSION.txt | tr -d '\n'
  yamllint:
    docker:
      - image: 'circleci/python:3.6.4'
    steps:
      - 'checkout'
      - run:
          name: 'install yamllint'
          command: 'sudo pip install yamllint'
      - run:
          name: 'run yamllint'
          command: 'yamllint ./ .yamllint'
  hadolint:
    docker:
      - image: 'hadolint/hadolint:latest-debian'
    steps:
      - 'checkout'
      - run:
          name: 'run hadolint'
          command: 'hadolint Dockerfile'
workflows:
  version: 2
  lint:
    jobs:
      - yamllint:
          filters:
            branches:
              ignore:
                - 'master'
      - 'hadolint'
  build_and_push_image:
    jobs:
      - image_tag
      - aws-ecr/build-and-push-image:
          requires:
            - image_tag
          account-url: AWS_ECR_ACCOUNT_URL
          context: 'aws-ecr-push'
          create-repo: false
          dockerfile: 'Dockerfile'
          profile-name: 'default'
          region: AWS_DEFAULT_REGION
          repo: 'novu/msdos'
          tag: ${IMAGE_TAG}
